spring:
  application:
    name: emconnect-api

  # Database Configuration
  datasource:
    url: jdbc:postgresql://ep-red-bonus-a15a09sv-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_8og4XcVJQKHC
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # RabbitMQ prod config
  rabbitmq:
    host: puffin.rmq2.cloudamqp.com
    port: 5672
    username: ainhkadl
    password: y-9ZnVKIQnGHe16ptxU1Kl3L6EACmCH_
    virtual-host: ainhkadl

    connection-timeout: 10000
    publisher-confirm-type: correlated
    publisher-returns: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


# Server Configuration
server:
  port: 8080

# Actuator (Health Checks)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# JWT Configuration
jwt:
  secret: myVerySecureSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm2024!
  expiration: 86400000  # 24 hours in ms

# Google OAuth Configuration
google:
  oauth:
    client-id: ${GOOGLE_OAUTH_CLIENT_ID:}  

# Ticket Configuration
ticket:
  qr:
    storage-path: ../ticket-worker/tickets/qr